model_list:
- model_name: gemini-2.5-flash
  litellm_params:
    model: gemini/gemini-2.5-flash
    api_key: os.environ/GEMINI_API_KEY
#   - model_name: "Anthropic"
#     litellm_params:
#       model: anthropic/*
#       api_key: os.environ/ANTHROPIC_API_KEY

#   - model_name: "OpenAI"
#     litellm_params:
#       model: openai/*
#       api_key: os.environ/OPENAI_API_KEY  

#   - model_name: "Xai"
#     litellm_params:
#       model: xai/*
#       api_key: os.environ/XAI_API_KEY

#   - model_name: "DeepSeek"
#     litellm_params:
#       model: deepseek/*
#       api_key: os.environ/DEEPSEEK_API_KEY

#   - model_name: "Perplexity"
#     litellm_params:
#       model: perplexity/*
#       api_key: os.environ/PERPLEXITY_API_KEY
# mcp_servers:
#   # HTTP Streamable Server
#   deepwiki_mcp:
#     url: "https://mcp.deepwiki.com/mcp"
#   # SSE Server
#   zapier_mcp:
#     url: "https://actions.zapier.com/mcp/sk-akxxxxx/sse"
  
#   # Full configuration with all optional fields
#   my_http_server:
#     url: "https://my-mcp-server.com/mcp"
#     transport: "http"
#     description: "My custom MCP server"

  

  # # Anthropic Models
  # - model_name: "claude-opus-4 (3/3 | $$$$)"
  #   litellm_params:
  #     model: anthropic/claude-opus-4-20250514
  #     api_key: os.environ/ANTHROPIC_API_KEY
  
  # - model_name: "claude-3-7-sonnet (3/3 | $$$)"
  #   litellm_params:
  #     model: anthropic/claude-3-7-sonnet-latest
  #     api_key: os.environ/ANTHROPIC_API_KEY
  
  # - model_name: "claude-sonnet-4 (3/3 | $$$)"
  #   litellm_params:
  #     model: anthropic/claude-sonnet-4-20250514
  #     api_key: os.environ/ANTHROPIC_API_KEY

  # # OpenAI Models  
  # - model_name: "gpt-4-1 (2/3 | $$)"
  #   litellm_params:
  #     model: openai/gpt-4.1
  #     api_key: os.environ/OPENAI_API_KEY
  
  # - model_name: "gpt-4-1-mini (2/3 | $)"
  #   litellm_params:
  #     model: openai/gpt-4.1-mini
  #     api_key: os.environ/OPENAI_API_KEY

  # # xAI Models
  # - model_name: "grok-3 (3/3 | $$$)"
  #   litellm_params:
  #     model: xai/grok-3
  #     api_key: os.environ/XAI_API_KEY
  
  # - model_name: "grok-3-mini (3/3 | $) 🌟"
  #   litellm_params:
  #     model: xai/grok-3-mini
  #     api_key: os.environ/XAI_API_KEY

  # # Google Gemini Models
  # - model_name: "gemini-2-5-pro (3/3 | $$)"
  #   litellm_params:
  #     model: gemini/gemini-2.5-pro-preview-06-05
  #     api_key: os.environ/GOOGLE_API_KEY
  
  # - model_name: "gemini-2-5-flash (3/3 | $) 🌟"
  #   litellm_params:
  #     model: gemini/gemini-2.5-flash
  #     api_key: os.environ/GOOGLE_API_KEY
  
  # - model_name: "gemini-2-0-flash (2/3 | $)"
  #   litellm_params:
  #     model: gemini/gemini-2.0-flash
  #     api_key: os.environ/GOOGLE_API_KEY

  # # DeepSeek Models
  # - model_name: "deepseek-r1 (3/3 | $) 🌟"
  #   litellm_params:
  #     model: deepseek/deepseek-r1-0528
  #     api_key: os.environ/DEEPSEEK_API_KEY
  
  # - model_name: "deepseek-v3 (2/3 | $)"
  #   litellm_params:
  #     model: deepseek/deepseek-v3
  #     api_key: os.environ/DEEPSEEK_API_KEY

#General Settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  ui_username: os.environ/UI_USERNAME
  ui_password: os.environ/UI_PASSWORD
  stream: true
  user_header_name: X-OpenWebUI-User-Name


  
# Optional: Rate Limiting
litellm_settings:
  default_rpm: 500
  default_tpm: 100000