
#General Settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  ui_username: os.environ/UI_USERNAME
  ui_password: os.environ/UI_PASSWORD
  stream: true
  user_header_name: X-OpenWebUI-User-Name
  forward_openai_org_id: true
  # Add CORS settings
  allowed_origins: ["*"]  # or specifically ["https://litellm.tekamar.ca", "http://localhost:3080"]


  
# Optional: Rate Limiting
litellm_settings:
    enable_json_schema_validation: True
